### ISSUE TITLE
Unable to load mod organizer profile

### ISSUE THREAD

**Issue by N9is** [Sonorous256/skyrim-mod-medic#1]
I have my CC imported to MO2, having none of the cc in the actual data folder. This causes problems trying to run the program with mods that use them as masters? After setting up the correct mo2 folders and running, after loading Bethesda record files, it gives the following error:
"Plugin (Bethesda) applied with the following messages.
Error while configuring Skyrim support: Missing master (ccasvsse001-almsivi.esm) requested by (Unofficial Skyrim Creation Club Content Patch.esl)"

Is the solution for the foreseeable future to just redownload/migrate the cc mods into the data folder or can they be made to be able to be read from the mo2 instance? (Also how does this affect cleaned vanilla esms in mo2?)

**Comment by lobotomy-x** [comment]
same issue here even after dropping the file directly in and then again when disabling the creation club patch. Otherwise really interesting and useful tool, but I'd hope to see this go open source to find the issue myself and tackle other issues like the lack of persistent paths in app or via an ini file.

**Comment by Sonorous256** [comment]
Cheers; I missed your comments since I wasn't checking github issues, though others commented on this issue in the reddit thread.
I'll post the first real build, with a fix for this creation club issue but here and on nexus in the next couple of days -- plus probably open up a couple of new days to communicate.

**Comment by lobotomy-x** [comment]
Glad to see this isn't abandoned as it's a promising tool. Are you planning to post the full source material as well? Feel there's so many bugs waiting to happen with the amount of variation in mod setups that it would be useful to crowd source some fixes until the tool is more robust

**Comment by Sonorous256** [comment]
I'm a little cautious about unintentionally appearing to make promises, so please don't interpret anything I say right now to be a promise. Right now my focus has been just to get a starter build out, and to start to build a community. The long term direction of the project is something I hope to discover with a community of users. Right now, I'm not sure that it's completely obvious what that should be: for example, to more people want to use it to manage their mod list, or do mod-makers want to use it to debug their own mods, etc.

Some of these things will become clearer over time; and if there's sustained interest, hopefully we can discuss bigger directional questions (but, again, this is months not days kind of thinking, and no promises).

For the moment it's yet to be seen if the community at large is even interested! So I don't want to get ahead of myself yet,

Obviously I'm very happy if there's coders like yourself who want to contribute and help the project grow. And there may be avenues where more people can leverage the tech to build new outcomes. I only ask that you take the perspective that what's important is where we get to in the longer term, rather than where we get to in the next few weeks.

**Comment by Sonorous256** [comment]
The central issue in this thread; that creation club content was handled incorrectly, has been addressed in build 0.2-beta.
mod-medic (like Skyrim) now loads creation-club record files between base skyrim record files and records files in plugins.txt based on a filename filter. That is, so long as the creation-club record files are in the "data" directory they will get loaded.
